request-headers:
  User-Agent: "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36"
  # Language for the results, e.g. en, es, ...
  Accept-Language: 'en'

request:
  url-base: https://www.amazon.com/
  parameters: s?k={keyword}
  # Term to search for
  keyword: smartphone

# Debug mode saves a copy of the failed requests. Debug log directory to save debug files
debug: True
debug-dir: "debug_logs"
# file to save output
log-file: "out.log"

# Number of attempts to retry a failed request, and seconds to wait until retry
request-attempts: 3
nap-request: 60

# Max number of pages to navigate. -1 for all the pages
max-pages: 3
# Max number of products to retrieve. -1 for all the products
max-products: 3
# Max number of questions per product to retrieve. -1 for all the questions
max-questions-per-product: 3
# Max number of answers per question to retrieve. -1 for all the answers
max-answers-per-question: 3

# Flag to determine if the scrapper will only save the product ids
save-prod-ids: True
# If this parameter is set, the value is the filename from where the scrapper will take the product ids
# and will not run in sequential (default) mode
scrap-prod-ids:
